### ISSUE TITLE
masonry-bottom div blocks content from interacation

### ISSUE THREAD

**Issue by mistressofjellyfish** [fuxingloh/vue-masonry-wall#21]
Hi,

first of all: thank you for your library!

During testing, I found that the masonry-bottom div blocks user interaction with the contents of the main masonry item. To fix this, I added `z-index`directives in my style, fixing a z-index of 3 for `.masonry-item` and a z-index of 1 for `.masonry-bottom`.

Because reasons, I am currently unable to submit a PR, but I thought I'd let you know.

**Comment by fuxingloh** [comment]
Many thanks, I added `z-index: -1` for masonry-bottom instead.
