### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by afuentesdp90** [fuxingloh/vue-masonry-wall#3]
Hi! 
First of all I want to say thank you for this vue-masonry-wall plugin. 
I was making a masonry grid images layout, like unsplash or pinterest, but I have some doubts. For example, can you explain me which options accepts vue-masonry-wall component. I know that there are width and padding. But these width what it references for? 
Can you make, if it's possible, make an example with nuxt.js and images photos instead of text?

Thank you very much.

If I can help you, contact me please.

👍

**Comment by fuxingloh** [comment]
#### Added a very very simple example for image.

[Live Demo: Image](https://nuxt-app.now.sh/vue-masonry-wall-image) > [Source Code](https://github.com/fuxingloh/nuxt-app/blob/0725466dcf2d3d5338573ca7612f38ecd8fa2fa0/components/examples/ExampleMasonryImage.vue)
